# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: web-cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-cafe
  template:
    metadata:
      labels:
        app: web-cafe
    spec:
      containers:
      - name: web-cafe
        image: muhresta/web-cafe:v1
        resources:
          limits:
            memory: 512Mi
          request:
            memory: 256Mi
            cpu: 1
        ports:
        - containerPort: 80