# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-cafe-app
  labels: web-cafe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-cafe-app
  template:
    metadata:
      labels:
        app: web-cafe-app
    spec:
      containers:
      - name: web-cafe-app
        image: muhresta/web-cafe-app:v1
        ports:
        - containerPort: 80